name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Shellcheck
      run: shellcheck bin/*

  plugin-test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ASDF
      run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf
    - name: Test plugin
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . $HOME/asdf/asdf.sh
        asdf plugin-test iblinter $GITHUB_WORKSPACE 'iblinter version'
